name: Battle Cat
awards:
  daily_login: 5    
  biography: 50
facebook:
  app_id: 303486038573
packs:
  founding_fee: 1000  
  member_bonus_modifier: 2
shops:
  opening_fee: 2000
humans:
  slavery_earnings_multiplier: 1
  release_multiplier: 250
communication:
  sign_endurance_cost: 3