development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bpn_development
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bpn_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: battlepetnetwork
  pool: 5
  username: battlepet
  password: catpiss
  host: mysql.battlepet.net
