# File: config/facebooker-mock.yml
# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site,
# change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.
 
development:
 api_key: d697e44ba780627c9e5960c332828b29
 secret_key: f4f3b348a608bd51890c937bf8afe61d
 canvas_page_name: battlecat
 callback_url: http://api.battlepet.net/facebook/
 pretty_errors: true
 set_asset_host_to_callback_url: true
 tunnel:
     public_host_username: ???
     public_host: www.???.com
     public_port: 8888
     local_port: 3000
     server_alive_interval: 0
test:
  api_key: d697e44ba780627c9e5960c332828b29
  secret_key: f4f3b348a608bd51890c937bf8afe61d
  canvas_page_name: battlecat
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
production:
  api_key: d697e44ba780627c9e5960c332828b29
  secret_key: f4f3b348a608bd51890c937bf8afe61d
  canvas_page_name: battlecat
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0